In [1]:
#Zadanie 1
import numpy as np

print("What's your name?")
name = input()

result = (name + " ") * 7
print(result)

for _ in range(5):
    print(name)
    

What's your name?
Adam
Adam Adam Adam Adam Adam Adam Adam 
Adam
Adam
Adam
Adam
Adam


In [13]:
#Zadanie 2
lista = [10,21,9,33,44,4,66,77,88,99]
print(lista)
print("*********")
filtered = filter(lambda a: a > 10, lista)
print(list(filtered))
print("*********")
for num in lista:
    if(num>10):
        print(num)
print("*********")
lista2 = [lista2 for lista2 in lista if lista2 > 10]
print(lista2)


[10, 21, 9, 33, 44, 4, 66, 77, 88, 99]
*********
[21, 33, 44, 66, 77, 88, 99]
*********
21
33
44
66
77
88
99
*********
[21, 33, 44, 66, 77, 88, 99]


In [14]:
#Zadanie 3
lista3 = list(range(50, 151))
podzielnie = [num for num in lista3 if num % 3 == 0 and num % 7 == 0]
print(podzielnie)



[63, 84, 105, 126, 147]


In [7]:
#Zadanie 4
slownik = {
    "Polska": "Warszawa",
    "Niemcy": "Berlin",
    "Francja": "Paryż",
    "Hiszpania": "Madryt",
    "Włochy": "Rzym",
    "Australia": "Canberra",
    "Austria": "Wiedeń",
    "Argentyna": "Buenos Aires",
    "Egipt": "Kair",
    "Grecja": "Ateny"
}

print(list(slownik.values()))
print("*********")

print([kraj for kraj, stolica in slownik.items() if stolica.startswith("A")])
print("*********")

print([kraj for kraj in slownik.keys() if "E" in kraj])
print("*********")



['Warszawa', 'Berlin', 'Paryż', 'Madryt', 'Rzym', 'Canberra', 'Wiedeń', 'Buenos Aires', 'Kair', 'Ateny']
*********
['Grecja']
*********
['Egipt']
*********


In [25]:
#Zadanie 5
int_numbers = [5, 2, 8, 10, 3, 15, 1, 20, 7, 6]
print("Najmniejsza liczba:", min(int_numbers))
print("Największa liczba:", max(int_numbers))

Najmniejsza liczba: 1
Największa liczba: 20


In [30]:
#Zadanie 6
losowane = np.random.rand(20)
print(losowane)
print("*********")
print("Srednia: ", np.mean(losowane))
print("Max: ", np.max(losowane))
print("Min: ", np.min(losowane))

[0.18961394 0.16150698 0.4594273  0.47933666 0.35686752 0.14802325
 0.28146356 0.87236886 0.65369347 0.10130076 0.93731156 0.3875477
 0.60791881 0.45013699 0.76489068 0.16447109 0.75024907 0.49620118
 0.91414671 0.36842723]
*********
Srednia:  0.47724516604175643
Max:  0.9373115619828274
Min:  0.10130075657431514


In [36]:
#Zadanie 7
tabelka = np.random.randint(5, 16, size=(10, 20))
print(tabelka)
print("*********")

print("Średnie wartości w wierszach: ", np.mean(tabelka, axis=1))
print("Max wartoścu w wierszach: ", np.max(tabelka, axis=1))
print("Pozycje max wartości w wierszach: ", np.argmax(tabelka, axis=1))


[[ 9 13 13 13  8 13 11 12 10 10 11 11  7 12 14  5 13 12  5 10]
 [10 11  8 12  7  7  7  9  9 13  7 14 13 12 14  9 12  9  7 15]
 [10  5  6  8 10 15  6 13  6 10 13  6  8  9 15 11 12  9  8  9]
 [15  7  8 14  6 10  5  7 12  5 15  5 11  8  6  8 15  6  5 15]
 [ 9 11  7  5 11  9 10  9  7 12  7  8 11 10 11  6 13  9 10 15]
 [10 13  5 14 15 14  6 15  8 15  9 11 14  6 15 10  9  6  5 14]
 [14 10  7  8  8 12 15 14  9 15  9  6 10 14 12 11 13  9  5 14]
 [ 7 13 15 10 15 15  5 14  5  6 12 10  6 12 14 15  5 14 12 10]
 [12 12  5 11  6  5  9  8 15  5  7 14 15 15 13 15 12 12 11  6]
 [14 11 13  7 11  8 11  7 15  6  9  5 13  7  6  7 10 10 11 12]]
*********
Średnie wartości w wierszach:  [10.6  10.25  9.45  9.15  9.5  10.7  10.75 10.75 10.4   9.65]
Max wartoścu w wierszach:  [14 15 15 15 15 15 15 15 15 15]
Pozycje max wartości w wierszach:  [14 19  5  0 19  4  6  2  8  8]


In [37]:
#Zadanie 8
def dodatnie(numbers):
    return [num for num in numbers if num > 0]

# Test funkcji
print(dodatnie([-5, 3, 0, -2, 6, -8, 10, 15]))

[3, 6, 10, 15]


In [6]:
#Zadanie 9
def liczbaLiter(slownik):
    iloscLiter = sum(len(kraj) + len(stolica) for kraj, stolica in slownik.items())
    return iloscLiter

# Test funkcji
print("Liczba liter: ", liczbaLiter(slownik))

Liczba liter:  134
