In [24]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_absolute_percentage_error

ImportError: cannot import name 'precission_score' from 'sklearn.metrics' (/home/maciejrudy/conda/envs/pandas130/lib/python3.9/site-packages/sklearn/metrics/__init__.py)

In [2]:
iris = load_iris()
X = iris.data
y = iris.target


In [3]:
print(type(X))
print(type(y))

X_train, X_val, y_train, y_val = train_test_split(X, y, train_size = 0.25, random_state = 42)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
kn = KNeighborsClassifier()
kn.fit(X_train, y_train)

KNeighborsClassifier()

In [5]:
y_predict_train = kn.predict(X_train)
y_predict_val = kn.predict(X_val)



In [6]:
score_val = accuracy_score(y_val, y_predict_val)
score_train = accuracy_score(y_val[:30], y_predict_train[:30])

In [7]:
print(score_val)
print(score_train)


0.9646017699115044
0.3


In [8]:
print(y_val[:15])
print(y_predict_val[:15])

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0]


In [9]:
type(y)

numpy.ndarray

In [10]:
len(y)

150

In [11]:
classification_report(y_val, y_predict_val)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        42\n           1       0.97      0.92      0.94        36\n           2       0.92      0.97      0.94        35\n\n    accuracy                           0.96       113\n   macro avg       0.96      0.96      0.96       113\nweighted avg       0.97      0.96      0.96       113\n'

In [12]:
confusion_matrix(y_val, y_predict_val)

array([[42,  0,  0],
       [ 0, 33,  3],
       [ 0,  1, 34]])

In [13]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [14]:
from sklearn.datasets import load_diabetes


In [15]:
diabetes = load_diabetes()
X2 = diabetes.data
y2 = diabetes.target


In [16]:
len(y2)

442

In [17]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, train_size = 0.75, random_state = 42)                         

In [18]:
kn2 = KNeighborsRegressor(n_neighbors = 7)

In [19]:
kn2.fit(X2_train, y2_train)
prediction_test = kn2.predict(X2_test)
#prediction_train =kn2.predict(X2_train)

In [20]:
mean_squared_error(y2_test, prediction_test)

3053.0610406324686

In [21]:
mean_absolute_percentage_error(y2_test, prediction_test)

0.36958824123053247

In [26]:
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import r2_score

In [31]:
f1_score(y_val, y_predict_val, average = 'macro')

0.9624338624338624

In [34]:
from sklearn.metrics import recall_score
recall_score(y_val, y_predict_val, average = 'micro')

0.9646017699115044

In [35]:
from sklearn.metrics import matthews_corrcoef

In [36]:
matthews_corrcoef(y_val, y_predict_val)

0.9471822946639211

In [37]:
from sklearn.datasets import make_regression, make_classification

In [41]:
X_data, y_target = make_regression(n_samples = 500, n_features = 4, random_state = 42)

In [50]:
A, B = make_classification(n_samples = 500, n_features = 10, n_classes = 5, n_informative = 5, random_state = 42)

In [52]:
A.size


5000

In [53]:
B.size

500

In [57]:
kAB = KNeighborsClassifier()

In [58]:
At, Av, Bt, Bv = train_test_split(A, B, train_size = 0.3, random_state = 42)

In [59]:
At.size

1500

In [60]:
kAB.fit(At,Bt)

KNeighborsClassifier()

In [62]:
predictions = kAB.predict(Av)


In [72]:
df = pd.DataFrame(classification_report(Bv, predictions, output_dict = True))

In [73]:
print(df.T)
print(df)

              precision    recall  f1-score  support
0              0.505618  0.671642  0.576923    67.00
1              0.746479  0.746479  0.746479    71.00
2              0.515625  0.478261  0.496241    69.00
3              0.725490  0.506849  0.596774    73.00
4              0.653333  0.700000  0.675862    70.00
accuracy       0.620000  0.620000  0.620000     0.62
macro avg      0.629309  0.620646  0.618456   350.00
weighted avg   0.631853  0.620000  0.619341   350.00
                   0          1          2          3          4  accuracy  \
precision   0.505618   0.746479   0.515625   0.725490   0.653333      0.62   
recall      0.671642   0.746479   0.478261   0.506849   0.700000      0.62   
f1-score    0.576923   0.746479   0.496241   0.596774   0.675862      0.62   
support    67.000000  71.000000  69.000000  73.000000  70.000000      0.62   

            macro avg  weighted avg  
precision    0.629309      0.631853  
recall       0.620646      0.620000  
f1-score     0.618